EspacoVivenciar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("apps.core.urls")),
    path('', include("apps.perfil.urls")),
    path('', include("apps.atendente.urls")),
    path('', include("apps.medico.urls")),
    path('', include("apps.paciente.urls")),
    path('', include("apps.agenda_medico.urls")),
    path('', include("apps.agendamento.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index, name="Index"),
]

apps/medico/urls.py
from django.urls import path
from . import views

app_name = 'medico'

urlpatterns = [
    path("atendente/profissionais/", views.ListarProfissionais.as_view(), name="listar-profissionais"),
    path("atendente/profissionais/cadastrar", views.CriarProfissional.as_view(), name="Cadastrar-Profissionais"),
    path('criar/servico/<int:profissional_pk>/', views.CriarServico.as_view(), name='criar-servico'),
    path('servico/', views.ListarServico.as_view(), name='listar-servico'),
    path('excluir-servico/<int:servico_pk>/<int:profissional_pk>/', views.ExcluirServico.as_view(), name='excluir-servico'),
    path('editar-servico/<int:servico_pk>/<int:profissional_pk>/', views.EditarServico.as_view(), name='editar-servico'),
    path("atendente/profissional/excluir/<int:id>", views.ExcluirProfissional.as_view(), name="excluir-profissional"),
    path('detalhe-profissional/<int:profissional_pk>/', views.DetalharProfissional.as_view(), name='detalhe-profissional'),
    path('editar-profissional/<int:profissional_pk>/', views.EditarProfissional.as_view(), name='editar-profissional'),

    
]

apps/paciente/urls.py
from django.urls import path
from . import views

app_name = 'paciente'

urlpatterns = [

    path("atendente/pacientes/", views.ListarPacientes.as_view(), name="listar-pacientes"),
    path("atendente/pacientes/criar", views.CriarPaciente.as_view(), name="criar-paciente"),
    path("atendente/pacientes/excluir/<int:id>", views.ExcluirPaciente.as_view(), name="excluir-paciente"),
    path("atendente/pacientes/editar/<int:id>", views.EditarPaciente.as_view(), name="editar-paciente"),
    path("paciente/home/", views.Home.as_view(), name="Home"),
    
    path('paciente/selecionar-agenda/<int:profissional_pk>/', views.SelecionarAgendaView.as_view(), name='selecionar_agenda'),
    path('paciente/agenda/<int:profissional_pk>/<int:servico_id>/', views.ListarAgenda.as_view(), name='listar-agendas'),
    path('agenda/solicitar/<int:agenda_id>', views.ListarHorarios.as_view(), name='listar-horarios-atendimento'),
      
]

apps/perfil/urls.py
from django.urls import path
from .views import ListarAgendamentos, DetalhesPaciente, HomeView, RegisterPacienteView, EditarPaciente, Login
from django.contrib.auth.views import LogoutView

app_name = 'perfil'

urlpatterns = [
    path("cadastro/", RegisterPacienteView.as_view(), name="Cadastro"),
    path("login/", Login.as_view(), name="Login"),
    path("logout/", LogoutView.as_view(), name="Logout"),
    path("home/", HomeView.as_view(), name="Home"),
    path('listar-agendamentos/', ListarAgendamentos.as_view(), name='listar-agendamentos'),
    path('perfil/detalhes/', DetalhesPaciente.as_view(), name='detalhes-paciente'),
    path('perfil/editar/', EditarPaciente.as_view(), name='editar-paciente'),
]

templates/partials/card_listar_paciente.html
{% load static %}
<div class="card-item-paciente">
    <div class="foto-nome">
        <div class="circle-avatar" id="patient-avatar">{{ paciente.nome_paciente.0 }}</div>
        <div class="user">
            <p class="name-paciente" >{{ paciente.nome_paciente }}</p>
            <p>{{ paciente.cpf_formatado }}</p>
            
        </div>
    </div>

    <div class="buttons">
        <a href = "{% url 'paciente:editar-paciente' id=paciente.id %}"><button class="lapis"><img src="{% static 'assets/img/icons/pencil.svg'%}" alt="lapis de edição">Editar</button></a>
        
        <a href = "{% url 'paciente:excluir-paciente' id=paciente.id %}"><button class="lixeira"><img src="{% static 'assets/img/icons/trash.svg'%}" alt="lixeira">Excluir</button></a>
    </div>
</div>

<script src="{% static 'paciente/js/foto-perfil.js' %}"></script>

templates/partials/card_profissional.html
{% load static %}
<div class="card-item-paciente">
    <div class="foto-nome">
        <img src="{{ profissional.imagem.url }}" alt="Imagem" id="imagem-profissional">
        <div class="user">
            <p class="name-paciente" style="width: 400px;">{{ profissional.nome_medico }}</p>
            <p style="width: 100px;" >{{ profissional.especialidade }}</p>
        </div>
    </div>
    

    <div class="buttons">
    
        <a href = "#' id=paciente.id %}"><button class="lapis"><img src="{% static 'assets/img/icons/pencil.svg'%}" alt="lapis de edição">Editar</button></a>
        
        <a href = "{% url "medico:excluir-profissional" id=profissional.id %}"><button class="lixeira"><img src="{% static 'assets/img/icons/trash.svg'%}" alt="lixeira">Excluir</button></a>
    </div>
</div>

templates/partials/cards.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'perfil/css/modal.css' %}">
<link rel="stylesheet" href="{% static 'atendente/css/modal-paciente.css' %}">
<link rel="stylesheet" href="{% static 'atendente/css/modal_selecionar.css' %}">

<div class="card-item">
    {% if card == "agendamento" %}
        {% if data %}
        <div class="data-hr">
            <div class="data">
                <h2>Seg</h2>
                <h3>28</h3>
            </div>
            <hr>
        </div>
        {% endif %}
        {% if info_user %}
            <img src="{% static "assets/img/icons/medico.svg" %}" alt="">
            <div class="user">
                <p class = "name">Dr. Kaio Moura<p>
                <p>Clínico geral</p>
            </div>
        {% endif %}

        {% if info_user2 %}
            <img src="{% static "assets/img/icons/paciente.svg" %}" alt="">
            <div class="user">
                <p class = "name">José da Silva<p>
            </div>
        {% endif %}

        {% if horario %}
            <div class="horario">   
                <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
                <p>9:00h - 10:00h</p>
            </div>
        {% endif %}

        {% if horario2 %}
        <div class="horario-solicitar">
            <p>Horários de atendimento</p>
            <div class="horario">
                <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
                <p>9:00h - 10:00h</p>
            </div>
        </div>
        {% endif %}

        {% if lista_servico %}
            <div class="list-service">
                <img src="{% static "assets/img/icons/motivo.svg" %}" alt="">
                <P>Motivo da consulta</P>
            </div>
        {% endif %}

        {% if count_agendados %}
        <div class="count-solicitacoes">
            <div class="qtd-agendados">
                <p>10</p>
            </div>
            <p>Agendamentos</p>
        </div>
        {% endif %}

        {% if count_solicitacoes %}
        <div class="count-solicitacoes">
            <div class="qtd-solicitacoes">
                <p>3</p>
            </div>
            <p>Solicitações</p>
        </div>
        {% endif %}

        {% if button_indeferido %}
            <button class="button_indeferido" data-toggle="modal" data-target="#pacienteModal"><img src="{% static "assets/img/icons/info.svg" %}" alt=""></button>
        {% endif %}

        {% if button_indeferido2 %}
        <button class="button_indeferido2" data-toggle="modal" data-target="#pacienteModal2"><img src="{% static "assets/img/icons/info.svg" %}" alt=""></button>
    {% endif %}

        {% if button_whastApp %}
            <a href=""><img src="{% static "assets/img/icons/whatsappbutton.svg" %}" alt=""></a>
        {% endif %}
        {% if button_detalhar %}
            <a href="{% url "atendente:Agendamentos-Solicitacoes" %}"><button class="button-detalhar">Detalhar</button></a>
        {% endif %}

        {% comment %} 
            Reagendar e cancelar
        {% endcomment %}
        {% if edit %}
        <div class="menu2">
            <button class="button_edit" id="toggleMenu">
                <img src="{% static "assets/img/icons/edit.svg" %}" alt="">
            </button>
            <div class="dropdown-menu2">
                <a href="#">Reagendar</a>
                <a  id="cancel" href="#">Cancelar</a>
            </div>
        </div>
        
        {% endif %}
        
        {% comment %} 
            editar, excluir ou criar
        {% endcomment %}
        {% if edit2 %}
        <div class="menu2">
            <button class="button_edit" id="toggleMenu">
                <img src="{% static "assets/img/icons/edit.svg" %}" alt="">
            </button>
            <div class="dropdown-menu2">
                <a  id="agendar" data-toggle="modal" data-target="#myModal_selecionar">Agendar</a>
                <a href="#">Editar</a>
                <a  id="cancel" href="#">Excluir</a>
            </div>
            {% comment %} <button class="button_edit2" data-toggle="modal" data-target="#myModal_selecionar"><img src="{% static "assets/img/icons/edit.svg" %}" alt=""></button> {% endcomment %}
        {% endif %}

        {% if button_solicitar %}
            <button class="btn-card" data-toggle="modal" data-target="#myModal1">Solicitar</button>
        {% endif %}

        {% if button_recusar %}
            <button class="button-recusar">Recusar</button>
        {% endif %}

        {% if button_aceitar %}
            <button class="button-aceitar">Aceitar</button>
        {% endif %}
    </div>
    {% endif %}

templates/partials/cards_solicitacao.html
{% load static %}
{%include "atendente/modal_paciente2.html"%}
<div class="card-item">

            <img src="{% static "assets/img/icons/paciente.svg" %}" alt="">
            <div class="user">
                <p class = "name">José da Silva<p>
            </div>

            <div class="horario">   
                <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
                <p>9:00h - 10:00h</p>
            </div>
 
            <div class="list-service">
                <img src="{% static "assets/img/icons/motivo.svg" %}" alt="">
                <P>Motivo da consulta</P>
            </div>

            <button class="button_indeferido" data-toggle="modal" data-target="#pacienteModal2"><img src="{% static "assets/img/icons/info.svg" %}" alt=""></button>

            <button class="button-recusar">Recusar</button>
            <button class="button-aceitar">Aceitar</button>
    </div>

templates/partials/footer.html
{% load static %}
<footer>
    <div class="container-footer">
        <div class="logo-footer">
            <img src="{% static 'assets/img/icons/Logo-footer.svg' %}" alt="">
        </div>

        <div class="localizacao-footer">
            <img src="" alt="">
            <p>Serrinha dos Pintos, Rua Tomaz Sampaio, Centro</p>
        </div>
        
        <nav class="nav-footer">
            <ul style="list-style-type: none;">
                <li>
                    <a href="https://www.facebook.com/profile.php?id=100095119054539&locale=pt_BR" target="_blank">
                        <img src="{% static "core/assets/img/icons/facebook.png" %}" alt="">
                    </a>
                </li>
                <li>
                    <a href="https://www.instagram.com/espacovivenciar1/?utm_source=ig_web_button_share_sheet&igshid=ODE2OTA4Y2Y1MQ==" target="_blank">
                        <img src="{% static "core/assets/img/icons/instagram.png" %}" alt="" >
                    </a>
                </li>
            </ul>
        </nav> 
    </div>
</footer>

templates/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Style -->
<link rel="stylesheet" href="{% static 'core/assets/css/style.css'%}">
<link rel="stylesheet" href="{% static 'assets/css/carousel.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

<!-- fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">

<!-- Scripts -->
<script src="{% static "core/assets/js/index.js" %}" defer></script>

<title>Espaço Vivenciar {% block title %}{% endblock title %}</title>

templates/partials/header.html
{% load static %}
<header>
    <div class="nav">
        <a href = "{% url "core:Index" %}"> <img  class = "home-logo" src= "{% static 'assets/img/icons/Logo.svg' %}" alt=""> </a>
        <a href="{% url "perfil:Login" %}"><button type="button" class="login-button">Entrar</a></button>
    </div>
</header>

templates/partials/header_icon.html
{% load static %}
<header>
    <div class="nav">
        <a href="{% url 'paciente:Home' %}">
            <img class="home-logo" src="{% static 'assets/img/icons/Logo.svg' %}" alt="">
        </a>
        <div class="menu">
            <img class="home-icon" src="{% static 'assets/img/icons/admin.svg' %}">
            <div class="dropdown-menu">
                <a href="{% url 'perfil:editar-paciente'%}">Meu Perfil</a>
                <a href="{% url 'perfil:listar-agendamentos' %}">Meus Agendamentos</a>

                <form class="sair-link" method='POST' action="{% url 'perfil:Logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="sair-link">Sair</button>
                </form>
            </div>
        </div>
    </div>
</header>

templates/partials/header_icon_atendente.html
{% load static %}
<header>
    <div class="nav">
        <a href="{% url 'agenda_medico:Home' %}">
            <img class="home-logo" src="{% static 'assets/img/icons/Logo.svg' %}" alt="">
        </a>
        <div class="menu">
            <img class="home-icon" src="{% static 'assets/img/icons/admin.svg' %}">
            <div class="dropdown-menu">
                <a href="{% url 'medico:listar-profissionais' %}">Gerenciar Profissionais</a>
                <a href="{% url "paciente:listar-pacientes" %}">Gerenciar Pacientes</a>

                <form class="sair-link" method='POST' action="{% url 'perfil:Logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="sair-link">Sair</button>
                </form>
            </div>
        </div>
    </div>
</header>   

templates/partials/pagination.html
{% if page_obj.has_other_pages %}
<div class="custom-pagination" role="group" aria-label="Item pagination">
    {% if page_obj.has_previous %}
        <a class='skip' href="?page={{ page_obj.previous_page_number }}"><</a>
    {% endif %}
    <div class='numeros'>
    {% for page_number in page_obj.paginator.page_range %}
        {% if page_obj.number == page_number %}
            <button class="active">
                <span class='page'>{{ page_number }} <span class="sr-only">(Atual)</span></span>
            </button>
        {% else %}
            <a class='page' href="?page={{ page_number }}">{{ page_number }}</a>
        {% endif %}
    {% endfor %}
    </div>

    {% if page_obj.has_next %}
        <a class='skip' href="?page={{ page_obj.next_page_number }}">></a>
    {% endif %}
</div>
{% endif %}