EspacoVivenciar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("apps.core.urls")),
    path('', include("apps.perfil.urls")),
    path('', include("apps.atendente.urls")),
    path('', include("apps.medico.urls")),
    path('', include("apps.paciente.urls")),
    path('', include("apps.agenda_medico.urls")),
    path('', include("apps.agendamento.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/agenda_medico/urls.py
from django.urls import path
from . import views

app_name = 'agenda_medico'

urlpatterns = [
    path("atendente/home/", views.Home.as_view(), name="Home"),
    path('selecionar-agenda/<int:profissional_pk>/', views.SelecionarAgendaView.as_view(), name='selecionar_agenda'),
    path('agenda/<int:profissional_pk>/<int:servico_id>/', views.ListarAgenda.as_view(), name='listar-agenda'),
    path('agenda/horarios-de-atendimento/<int:agenda_id>', views.ListarHorarios.as_view(), name='listar-horarios'),   
    path('agenda/criar/<int:profissional_pk>/<int:servico_id>', views.CriarAgendaView.as_view(), name='criar-agenda'),
    path('agenda/excluir/<int:agenda_pk>/', views.ExcluirAgenda.as_view(), name='excluir-agenda'),
    path('horarios-de-atendimento/excluir/<int:agenda_pk>/<int:horario_pk>', views.ExcluirHorario.as_view(), name='excluir-horario'),
]

apps/agendamento/urls.py
from django.urls import path
from . import views

app_name = 'agendamento'

urlpatterns = [
    path('criar-agendamento/<int:horario_pk>/', views.CriarAgendamento.as_view(), name='criar-agendamento'), 
    path('agenda/agendamentos/<int:agenda_pk>/', views.ListarAgendamentosSolicitacoes.as_view(), name='listar-agendamentos'),
    path('aceitar_recusar_solicitacao/<int:solicitacao_id>/<str:action>/', views.AceitarRecusarSolicitacaoView.as_view(), name='aceitar_recusar_solicitacao'),
    path('solicitar-agendamento/<int:horario_pk>/', views.CriarSolicitacao.as_view(), name='solicitar-agendamento'),

]

apps/agenda_medico/models.py
from django.db import models
from datetime import  datetime, timedelta
from django.core.exceptions import ValidationError
from apps.medico.models import Profissional, Servico

class AgendaMedica(models.Model):
    profissional = models.ForeignKey(Profissional, on_delete = models.PROTECT, null = True, blank = True)
    data = models.DateField()
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE, null = True, blank = True)
    horario_inicio = models.TimeField(verbose_name = 'Horário de início')
    horario_fim = models.TimeField(verbose_name = 'Horário de fim')

    def get_count_agendamentos(self):
        return self.agendamentos.count()

    def get_count_solicitacoes(self):
        return self.solicitacoes.count()

    def get_duracao_servico(self):
        if self.servico:
            duracao_servico = timedelta(minutes=self.servico.duracao_total_minutos())
            return duracao_servico
        return timedelta()
    
    def get_horario_inicio(self):
        horario_inicio = datetime.combine(self.data, self.horario_inicio)
        return horario_inicio
    
    def get_horario_fim(self):
        horario_fim = datetime.combine(self.data, self.horario_fim)
        return horario_fim
    
    def gerar_horarios_atendimento(self):
        duracao_servico = self.get_duracao_servico()
        horario_inicio = self.get_horario_inicio()
        horario_fim = self.get_horario_fim()

        while horario_inicio < horario_fim:
            horario_fim_atendimento = horario_inicio + duracao_servico

            if horario_fim_atendimento <= horario_fim:

                horario = Horario.objects.create(
                agenda_medica = self,
                inicio = horario_inicio.time(),
                fim = horario_fim_atendimento.time(),
                disponivel = True  # ou o valor apropriado para disponibilidade
                )

            horario_inicio += duracao_servico

    def clean(self):

        conflito = AgendaMedica.objects.filter(

            profissional = self.profissional,
            data = self.data,
            horario_inicio__lt = self.horario_fim,
            horario_fim__gt = self.horario_inicio

        ).exclude(pk = self.pk)  # Excluir a própria agenda ao editar
        horario_inicio = self.get_horario_inicio()
        horario_fim = self.get_horario_fim()
        duracao_servico = self.get_duracao_servico()
        intervalo_disponivel = horario_fim - horario_inicio

        if conflito.exists():
            raise ValidationError('Conflito de horários com outras agendas do mesmo profissional.')
        
        elif horario_inicio > horario_fim:
            raise ValidationError('O intervalo de horários é inválido!')
        
        elif intervalo_disponivel < duracao_servico:
            raise ValidationError('O tempo é insuficiente! se deseja continuar, aumente o horário da agenda.')


    def save(self, *args, **kwargs):
        self.full_clean()  # Chama a validação clean antes de salvar
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Agenda de {self.profissional.nome_medico} em {self.data}'
    
class Horario(models.Model):
    agenda_medica = models.ForeignKey(AgendaMedica, on_delete = models.CASCADE, blank = True, related_name = 'horario_selecionado')
    inicio = models.TimeField()
    fim = models.TimeField()
    disponivel = models.BooleanField( default = True)

    def __str__(self):
        return f'{self.inicio} - {self.fim} - {self.disponivel}'

apps/agenda_medico/forms.py
from django import forms
from apps.medico.models import Profissional, Servico
from .models import AgendaMedica
import re
class SelecionarAgendaForm(forms.Form):
    servico = forms.ModelChoiceField(queryset=Servico.objects.none(), label='Selecione o serviço', widget=forms.Select(attrs={'class': 'edit-field'}))

    def __init__(self, *args, **kwargs):
        profissional = kwargs.pop('profissional', None)
        super(SelecionarAgendaForm, self).__init__(*args, **kwargs)
        if profissional:
            self.fields['servico'].queryset = profissional.servico_set.all()

class CustomDateInput(forms.DateInput):
    def format_value(self, value):
        if value:
            return value.strftime('%d/%m/%Y')
        return value

class AgendaMedicaForm(forms.ModelForm):
    data = forms.DateField(
        widget=CustomDateInput(attrs={'class': 'edit-field', 'placeholder': 'dd/mm/aaaa', 'type': 'date'}),
        input_formats=['%d/%m/%Y', '%Y/%m/%d', '%d-%m-%Y', '%Y-%m-%d'],
    )
    class Meta:
        model = AgendaMedica
        exclude = ['profissional', 'servico']
        widgets = {
        'horario_inicio': forms.TimeInput(attrs={'class': 'edit-field', 'placeholder': '00:00'}),
        'horario_fim': forms.TimeInput(attrs={'class': 'edit-field', 'placeholder': '00:00'}),
    }

apps/agenda_medico/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, View
from apps.medico.models import Profissional, Servico
from .models import AgendaMedica, Horario
from .forms import SelecionarAgendaForm, AgendaMedicaForm
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.agendamento.models import Agendamento, Solicitacao

class Home(LoginRequiredMixin, ListView):
    model = Profissional
    template_name = 'agenda_medico/home.html'
    context_object_name = 'profissionais'

class SelecionarAgendaView(FormView):
    template_name = 'agenda_medico/modal_escolher_agenda.html'
    form_class = SelecionarAgendaForm
    pk_url_kwarg = 'profissional_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        context['profissional'] = profissional
        context['servicos'] = profissional.servico_set.all()
        return context

    def form_valid(self, form):
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        servico = form.cleaned_data['servico']
        
        self.cleaned_data = {'servico': servico}

        return super().form_valid(form)

    def get_success_url(self):
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        servico = self.cleaned_data['servico']

        return reverse_lazy('agenda_medico:listar-agenda', kwargs={'profissional_pk': profissional_pk, 'servico_id': servico.id})

    def get_form_kwargs(self):
        kwarg = super().get_form_kwargs()
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        kwarg['profissional'] = profissional
        return kwarg


class ListarAgenda(ListView):
    model = AgendaMedica
    template_name = 'agenda_medico/gerenciar_agenda.html'
    context_object_name = 'agendas'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        servico_id = self.kwargs.get('servico_id')
        profissional = Profissional.objects.get(pk=profissional_pk)
        context['profissional'] = profissional
        context['servico'] = profissional.servico_set.get(id=servico_id)
        context['agendas'] = profissional.agendamedica_set.filter(servico=context['servico'])
        context['servico_id'] = servico_id
        context['profissional_pk'] = profissional_pk

        for agenda in context['agendas']:
            agenda.dia_semana_abreviado = listar_dias_semana(agenda)

            # Add the counts to each agenda
            agenda.agendamentos_count = Agendamento.objects.filter(horario_selecionado__agenda_medica=agenda).count()
            agenda.solicitacoes_count = Solicitacao.objects.filter(horario_selecionado__agenda_medica=agenda).count()

        return context

def listar_dias_semana(agenda):
    dias_da_semana = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom']
    dia_semana_numero = agenda.data.weekday()
    return dias_da_semana[dia_semana_numero]

class CriarAgendaView(CreateView):
    model = AgendaMedica
    form_class = AgendaMedicaForm
    template_name = 'agenda_medico/modal_criar_agenda.html'
    success_url = reverse_lazy('agenda_medico:listar-agenda')

    def form_valid(self, form):
        profissional_pk = self.kwargs.get('profissional_pk')
        servico_id = self.kwargs.get('servico_id')

        servico = Servico.objects.get(id=servico_id)
        profissional = Profissional.objects.get(pk=profissional_pk)
    
        form.instance.profissional = profissional
        form.instance.servico = servico

        agenda_medica_instance = form.save()

        # Chama o método para gerar os horários da agenda
        agenda_medica_instance.gerar_horarios_atendimento()

        return super().form_valid(form)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        servico_id = self.kwargs.get('servico_id')

        # Certifique-se de que está passando o objeto Servico corretamente para o contexto
        servico = Servico.objects.get(id=servico_id)
        profissional = Profissional.objects.get(pk=profissional_pk)

        context['profissional_pk'] = profissional_pk
        context['servico_id'] = servico_id
        context['servico'] = servico
        context['profissional'] = profissional

        return context
    
    def get_success_url(self):
        profissional_pk = self.kwargs.get('profissional_pk')
        servico_id = self.kwargs.get('servico_id')
        return reverse_lazy('agenda_medico:listar-agenda', kwargs={'profissional_pk': profissional_pk, 'servico_id': servico_id})
    
class ExcluirAgenda(DeleteView):
    model = AgendaMedica
    template_name = 'agenda_medico/excluir_agenda.html'  
    success_url = reverse_lazy('agenda_medico:listar-agenda')
    pk_url_kwarg = 'agenda_pk'

    def get_success_url(self):
        profissional_pk = self.object.profissional.pk
        servico_id = self.object.servico.id
        return reverse_lazy('agenda_medico:listar-agenda', kwargs={'profissional_pk': profissional_pk, 'servico_id': servico_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        agenda = self.object
        context['profissional_pk'] = agenda.profissional.pk
        context['servico_id'] = agenda.servico.id
        context['agenda_pk'] = agenda.pk
        print(agenda.pk)
       
        return context
    

class ListarHorarios(ListView):
    model = Horario
    template_name = 'agenda_medico/listar_horarios.html'
    context_object_name = 'horarios'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        agenda_id = self.kwargs.get('agenda_id')
        agenda = AgendaMedica.objects.get(id=agenda_id)
        context['agenda'] = agenda
        context['dia_semana_abreviado'] = listar_dias_semana(agenda)
        return context

    def get_queryset(self):
        agenda_id = self.kwargs.get('agenda_id')
        return Horario.objects.filter(agenda_medica__id=agenda_id)


class ExcluirHorario(DeleteView):
    model = Horario
    template_name = 'agenda_medico/excluir_horario.html' 
    pk_url_kwarg = 'horario_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        agenda_pk = self.kwargs.get('agenda_pk')
        horario_pk = self.kwargs.get('horario_pk')
        agenda = AgendaMedica.objects.get(id=agenda_pk)
        context['agenda'] = agenda
        context['agenda_pk'] = agenda_pk
        return context
    
    def get_success_url(self):
        agenda_pk = self.kwargs.get('agenda_pk')
        return reverse_lazy('agenda_medico:listar-horarios', kwargs={'agenda_id': agenda_pk})

apps/agenda_medico/templates/agenda_medico/card_agenda.html
{% load static %}
<div class="card-item {% if agenda.data == data_mais_proxima %} id="data-proxima" {% endif %}">
    <div class="data-hr">
        <div class="data">
            <h2>{{ agenda.dia_semana_abreviado }}</h2>
            <h3>{{ agenda.data.day }}</h3>
        </div>
        <hr>
    </div>
    <div class="horario-solicitar">
        <p class="horario-atendimento">Horários de atendimento</p>
        <div class="horario">
            <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
            <p>{{ agenda.horario_inicio }}h  - {{ agenda.horario_fim }}h</p>
        </div>
    </div>

    <div class="count-solicitacoes">
        <div class="qtd-agendados">
            <p>{{ agenda.agendamentos_count }}</p>
        </div>
        <p class= 'agenda-p'>Agendamentos</p>
    </div>

 
    <div class="count-solicitacoes">
        <div class="qtd-solicitacoes">
            <p>{{ agenda.solicitacoes_count }}</p>
        </div>
        <p class= 'agenda-p'>Solicitações</p>
    </div>

    <a href="{% url "agendamento:listar-agendamentos" agenda_pk=agenda.pk %}"><button class="button-detalhar">Detalhar</button></a>
    
    <div class="menu2">
        <button class="button_edit" id="toggleMenu">
            <img src="{% static "assets/img/icons/edit.svg" %}" alt="">
        </button>
        <div class="dropdown-menu2">
            <button onclick="window.location.href='{% url "agenda_medico:listar-horarios" agenda_id=agenda.id %}'">
                Ver Horários
            </button>
            
            <button  class='abrirModal5' id="cancel" hx-get="{% url 'agenda_medico:excluir-agenda' agenda_pk=agenda.pk %}" hx-trigger='click' hx-target='#modal5' hx-swap="innerHTML">Excluir</button>
        </div>
    </div>   

</div>

apps/agenda_medico/templates/agenda_medico/card_horario.html
{% load static %}
<div class="card-item-hora">
    <div class = "card-first">
            <div class= 'card-first-1'>
            <div class="data-hr">
                <div class="data2">
                    <h2>{{ dia_semana_abreviado }}</h2>
                    <h3>{{ agenda.data.day }}</h3>
                </div>
                <hr id ='hr'>
            </div>

            <div class="user">
                <p class = "name">{{ agenda.profissional.nome_medico}}<p>
                <p class = 'especialidade'>{{ agenda.profissional.especialidade}}</p>
            </div>
    </div>

    <div class="horario-solicitar">
        <p class="horario-atendimento">Tempo de duração</p>
        <div class="horario">
            <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
            <p class = 'hora'>{{ horario.inicio }}h  - {{ horario.fim}}h</p>
        </div>
    </div>
</div>

<div class="space-buttons">
    <div class="buttons">
        <button class='abrirModal7' hx-get="{% url 'agendamento:criar-agendamento' horario_pk=horario.pk %}"hx-trigger='click' hx-target='#modal7' hx-swap="innerHTML" id="lapis">
            <img src="{% static 'assets/img/icons/la_user-clock.svg' %}"  alt="lapis de edição">Agendar
        </button>
        

        <button class='abrirModal6' id="lixeira" hx-get="{% url 'agenda_medico:excluir-horario' agenda_pk=agenda.pk horario_pk=horario.pk%}" hx-trigger='click' hx-target='#modal6' hx-swap="innerHTML"><img src="{% static 'assets/img/icons/trash.svg'%}" alt="lixeira">Excluir</button></a>
    </div>
</div>
</div>

apps/agenda_medico/templates/agenda_medico/excluir_agenda.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal-2">Confirmação de Exclusão</p>
  <p class="confirmacao">Tem certeza que deseja excluir a agenda?</p>
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'agenda_medico:excluir-agenda' agenda_pk=agenda_pk %}" >
    {% csrf_token %}
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente-2" type="submit">Confirmar</button>
    </div>
  </form>
 </div> 

apps/agenda_medico/templates/agenda_medico/excluir_horario.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal-2">Excluir Horário</p>
  <p class="confirmacao">Tem certeza que deseja excluir o horário?</p>
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'agenda_medico:excluir-horario' agenda_pk=agenda_pk horario_pk=horario.pk %}" >
    {% csrf_token %}
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente-2" type="submit">Confirmar</button>
    </div>
  </form>
 </div> 

apps/agenda_medico/templates/agenda_medico/gerenciar_agenda.html
{% extends "base/base_home_atendente.html" %}
{% load static %}
{% block cadastrar_agenda %}
<div class="container">
    <div class="card-list">
        <div class="title">
            <h1>Agenda - {{ servico.nome_servico }}  </h1>
        </div>
        <div class="content">
            
            <dialog id="myModal4">
                <div id="modal4">
                </div>
            </dialog>
            
            <dialog class="myModal5">
                <div id="modal5">
                </div>
            </dialog>
                
                <div class="data-alternada">
                    <p>Dezembro</p> 
                </div>
                
                <div class="button-cadastrar-agenda">
                    <button class="btn-novaAgenda" id="abrirModal4" hx-get={% url 'agenda_medico:criar-agenda' profissional_pk=profissional_pk servico_id=servico_id%} hx-trigger='click' hx-target='#modal4' hx-swap="innerHTML">
                        <i class="ph ph-user-circle-plus"></i>
                        + Nova agenda
                      </button>
                    </div>
                    
                </div>

                {% for agenda in agendas %}
                    {% include "agenda_medico/card_agenda.html"   %}
                {% endfor %}

        </div>
    </div>
{% endblock cadastrar_agenda %}

apps/agenda_medico/templates/agenda_medico/home.html
{% extends "base/base_home_atendente.html" %}
{% load static %}
{% block home_atendente %}

<dialog class="myModal3">
  <div id="modal3">
  </div>
</dialog>

<div class="container">
  <div class="home-info">
      <p>Bem-vindo(a)!</p>
      <h1>Sistema de Agendamentos</h1>
      <br>
      <p>Escolha um especialista e gerencie agendamentos <br> e solicitacoes.</p>
  </div>

  <div class="home-img">
      <img src="{% static "assets/img/home-img.svg" %}" alt="">
  </div>
</div>

<div class="wrapper">
  <i id="left" class="fa-solid fa-angle-left"></i>
  <ul class="carousel">
    {% for profissional in profissionais %}

    <button class="abrirModal3" hx-get="{% url 'agenda_medico:selecionar_agenda' profissional_pk=profissional.pk %}"
      hx-trigger='click' hx-target='#modal3' hx-swap="innerHTML">
      <li class="card">
        {% include "partials/card-carousel.html" %}
      </li>
    </button>

    {% endfor %}
  </ul>
  <i id="right" class="fa-solid fa-angle-right"></i>
</div>

{% endblock home_atendente %}

apps/agenda_medico/templates/agenda_medico/listar_horarios.html
{% extends "base/base_home_atendente.html" %}
{% load static %}

{% block cadastrar_agenda %}
    <div class="container">

        <dialog class="myModal6">
            <div id="modal6">
            </div>
        </dialog>

        <dialog class="myModal7">
            <div id="modal7">
            </div>
        </dialog>
        
        <div class="card-list">
            
            <div class="title">
                <h1>Horários disponíveis - {{ agenda.servico.nome_servico }}  </h1>
            </div>
            


            {% for horario in horarios %}
                    {% include "agenda_medico/card_horario.html"   %}
                    
            {% endfor %}

        </div>
    </div>
    {% include "partials/pagination.html" %}

{% endblock cadastrar_agenda %}

apps/agenda_medico/templates/agenda_medico/modal_criar_agenda.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal">Criar agenda - {{ servico.nome_servico }}</p> 
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'agenda_medico:criar-agenda' profissional_pk=profissional_pk servico_id=servico_id%}">

    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente" type="submit">Salvar</button>
    </div>
  </form>
 </div> 

apps/agenda_medico/templates/agenda_medico/modal_escolher_agenda.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal">Selecionar agenda</p> 
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'agenda_medico:selecionar_agenda' profissional_pk=profissional.pk %}">

    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente" type="submit">Confirmar</button>
    </div>
  </form>
 </div> 

apps/agenda_medico/templates/agenda_medico/modal_selecionar_paciente.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal">Criar agendamento</p> 
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'agendamento:criar-agendamento' horario_pk=horario_pk %}">

    {% csrf_token %}emodel
    {% for paciente in pacientes %}
      <div>
        <input type="radio" name="paciente_id" class="opcao1" value="{{ paciente.id }}" id="opcao{{ paciente.id }}">
        <label for="opcao{{ paciente.id }}">
          <div class="paciente">
            <div class="foto-nome">
              <div class="circle-avatar" id="patient-avatar">{{ paciente.nome_paciente.0 }}</div>
              <div class="user">
                <p class="name-paciente">{{ paciente.nome_paciente }}</p>
                <p>{{ paciente.cpf_formatado }}</p>
              </div>
            </div>
          </div>
        </label>
      </div>
    {% endfor %}
    {{form.errors}}
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente" type="submit">Confirmar</button>
    </div>
  </form>
 </div> 