EspacoVivenciar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("apps.core.urls")),
    path('', include("apps.perfil.urls")),
    path('', include("apps.atendente.urls")),
    path('', include("apps.medico.urls")),
    path('', include("apps.paciente.urls")),
    path('', include("apps.agenda_medico.urls")),
    path('', include("apps.agendamento.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/medico/urls.py
from django.urls import path
from . import views

app_name = 'medico'

urlpatterns = [
    path("atendente/profissionais/", views.ListarProfissionais.as_view(), name="listar-profissionais"),
    path("atendente/profissionais/cadastrar", views.CriarProfissional.as_view(), name="Cadastrar-Profissionais"),
    path('criar/servico/<int:profissional_pk>/', views.CriarServico.as_view(), name='criar-servico'),
    path('servico/', views.ListarServico.as_view(), name='listar-servico'),
    path('excluir-servico/<int:servico_pk>/<int:profissional_pk>/', views.ExcluirServico.as_view(), name='excluir-servico'),
    path('editar-servico/<int:servico_pk>/<int:profissional_pk>/', views.EditarServico.as_view(), name='editar-servico'),
    path("atendente/profissional/excluir/<int:id>", views.ExcluirProfissional.as_view(), name="excluir-profissional"),
    path('detalhe-profissional/<int:profissional_pk>/', views.DetalharProfissional.as_view(), name='detalhe-profissional'),
    path('editar-profissional/<int:profissional_pk>/', views.EditarProfissional.as_view(), name='editar-profissional'),

    
]

apps/medico/models.py
from django.db import models
from django.db.models import ProtectedError

class Profissional(models.Model):
    imagem = models.ImageField(upload_to =' media')
    numero_registro = models.CharField( verbose_name= 'Registro Profissional', max_length = 20)
    nome_medico = models.CharField('Nome', max_length = 200)
    especialidade = models.CharField('Especialidade', max_length = 200)
    contato_profissional = models.CharField('Contato', max_length = 15, unique = True, null = True )

    def __str__(self):
        return f'Nome: {self.nome_medico} - {self.especialidade}'
    
    class Meta:
        verbose_name_plural = 'Profissionais'
     
class Servico(models.Model):
    nome_servico = models.CharField('Nome', max_length= 200)
    duracao_horas = models.PositiveIntegerField( default= 0)
    duracao_minutos = models.PositiveIntegerField( default= 0)
    profissional = models.ForeignKey(Profissional, on_delete = models.CASCADE)

    def duracao_total_minutos(self):
        return self.duracao_horas * 60 + self.duracao_minutos

    def __str__(self):
        return f'{self.nome_servico}'
    

apps/medico/forms.py
from django import forms
from apps.medico.models import Profissional, Servico
from django.forms import inlineformset_factory

class ProfissionalForm(forms.ModelForm):
    class Meta:
        model = Profissional
        fields = '__all__'
        widgets = {
        'nome_medico' : forms.TextInput(attrs={'class': 'edit-field' }),
        'especialidade' : forms.TextInput(attrs={'class': 'edit-field' }),
        'numero_registro' : forms.TextInput(attrs={'class': 'edit-field' }),
        'contato_profissional' : forms.TextInput(attrs={'class': 'edit-field' }),
        'imagem' : forms.FileInput(attrs={'class': 'edit-field' }),

        
    }

class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        exclude = ['profissional']
        widgets = {
        'nome_servico' : forms.TextInput(attrs={'class': 'edit-field' }),
        'duracao_horas': forms.NumberInput(attrs={'class': 'edit-field'}),
        'duracao_minutos': forms.NumberInput(attrs={'class': 'edit-field'}),
    }

apps/medico/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from django.db.models import Q
from django.urls import reverse_lazy
from apps.medico.models import Profissional, Servico
from .forms import ServicoForm, ProfissionalForm
from django.contrib import messages

class ListarProfissionais(ListView):
    model = Profissional
    template_name = 'medico/listar_profissionais.html'
    context_object_name = 'profissionais'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('search')
        object_list = Profissional.objects.all()

        if query:
            object_list = object_list.filter(Q(nome_medico__icontains=query)| Q(especialidade__icontains=query))
        return object_list
    
    def home_atendente(request):
        profissionais = Profissional.objects.all()
        return render(request, 'atendente/home.html', {'profissionais': profissionais})

    def home_paciente(request):
        profissionais = Profissional.objects.all()
        return render(request, 'paciente/home.html', {'profissionais': profissionais})

class CriarProfissional(CreateView):
    model = Profissional
    form_class = ProfissionalForm
    template_name = 'medico/novo_profissional.html'
    success_url = reverse_lazy('medico:listar-profissionais')

    def get_success_url(self):
        return reverse('medico:detalhe-profissional', kwargs={'profissional_pk': self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        return redirect(self.get_success_url())


class ExcluirProfissional(DeleteView):
    model = Profissional
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('medico:listar-profissionais')

    def get(self, *args, **kwargs):
        return self.delete(*args, **kwargs)


class EditarProfissional(UpdateView):
    model = Profissional
    form_class = ProfissionalForm
    template_name = 'medico/novo_profissional.html'
    pk_url_kwarg = 'profissional_pk'

    def get_success_url(self):
        # Após salvar o serviço, redirecione de volta para a página de detalhes do profissional
        return reverse('medico:detalhe-profissional', kwargs={'profissional_pk': self.object.pk})

class CriarServico(CreateView):
    model = Servico
    form_class = ServicoForm
    template_name = 'medico/modal_add_service.html'
    success_url = reverse_lazy('medico:detalhe-profissional')  # Mudado para detalhe-profissional

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        context['profissional_pk'] = profissional_pk
        context['profissional'] = profissional
        return context
    
    def form_valid(self, form):
        # Antes de salvar o formulário, defina o profissional com base no contexto
        form.instance.profissional = self.get_context_data()['profissional']
        response = super().form_valid(form)
        return redirect(self.get_success_url())

    def get_success_url(self):
        # Após salvar o serviço, redirecione de volta para a página de detalhes do profissional
        return reverse('medico:detalhe-profissional', kwargs={'profissional_pk': self.get_context_data()['profissional_pk']})

class ListarServico(ListView):
    model = Servico
    template_name = 'medico/cadastrar-servicos.html'
    context_object_name = 'servicos'  

class DetalharProfissional(DetailView):
    model = Profissional
    template_name = 'medico/adicionar_servicos.html'
    context_object_name = 'profissional'
    pk_url_kwarg = 'profissional_pk'
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional = context[self.context_object_name]
        context['servicos'] = profissional.servico_set.all()
        return context
    
class ExcluirServico(DeleteView):
    model = Servico
    success_url = reverse_lazy('medico:detalhe-profissional')
    pk_url_kwarg = 'servico_pk'

    def get_success_url(self):
        profissional_pk = self.kwargs['profissional_pk']
        return reverse_lazy('medico:detalhe-profissional', kwargs={'profissional_pk': profissional_pk})

    def get(self, *args, **kwargs):
        return self.delete(*args, **kwargs)
    
class EditarServico(UpdateView):
    model = Servico
    form_class = ServicoForm
    template_name = 'medico/modal_edit_service.html'
    context_object_name = 'servico'
    pk_url_kwarg = 'servico_pk'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk = profissional_pk)
        context['profissional_pk'] = profissional_pk
        context['profissional'] = profissional
        return context

    def get_success_url(self):
        profissional_pk = self.kwargs['profissional_pk']
        return reverse_lazy('medico:detalhe-profissional', kwargs={'profissional_pk': profissional_pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        return redirect(self.get_success_url())

apps/medico/templates/medico/adicionar_servicos.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'atendente/css/novo-profissional.css' %}">
    <link rel="stylesheet" href="{% static 'perfil/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'medico/css/modal.css' %}">
    <script src="{% static 'medico/js/modal.js' %}"></script>
    <link rel="stylesheet" href="{% static 'perfil/css/modal.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.9" integrity="sha384-QFjmbokDn2DjBjq+fM+8LUIVrAgqcNW2s0PjAxHETgRn9l4fvX31ZxDxvwQnyMOX" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Gerenciar Profissionais</title>
</head>
<body>
    {% include "partials/header_icon_atendente.html" %}
    <div class="container">
        <h1>Cadastrar Profissional</h1>
        <main>
            <section class="card-info">
                    {% csrf_token %}
                    <div class="card-header">
                        <h2>Informações pessoais</h2>
                        <div>
                            <a href = "{% url 'medico:editar-profissional' profissional_pk=profissional.pk %}">
                                <button id="salvarButton">Editar</button>
                            </a>
                        </div> 
                    </div>
                    <div class="info-user">
            
                        <img src="{{ profissional.imagem.url }}" alt="Imagem" id="imagem-profissional">
                           
                            <div>
                            <div class="first-section">
                                <div class="campos">
                                    <label for="nome">Nome</label>
                                    <p>{{ profissional.nome_medico }}</p>
                                </div>
                                <div class="campos">
                                    <label for="data">Registro Profissional</label>
                                    <p>{{ profissional.numero_registro }}</p>
                                </div>
                            </div>
                        <div class="sections">
                            <div class="second-section">
                                <div class="campos">
                                    <label for="e-mail">Especialidade</label>
                                    <p>{{ profissional.especialidade }}</p>
                                </div>
                            </div>
                            <div class="third-section">
                                <div class="campos">
                                    <label for="contato">Contato</label>
                                    <p>{{ profissional.contato_profissional }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                  
            </section>
    

<section class="card-info">
    <div class="card-header">
        <h2>Serviços Oferecidos</h2>
        <button class="add-service" id="abrirModal" hx-get={% url 'medico:criar-servico' profissional_pk=profissional.pk %} hx-trigger='click' hx-target='#modal' hx-swap="innerHTML">
            <i class="ph ph-user-circle-plus"></i>
            Novo Serviço
          </button> 

        <dialog class="cadastro-de-paciente" id="myModal">
            <div id="modal">
            </div>
        </dialog>

        <dialog class="myModal2">
            <div class="modal2">
            </div>
        </dialog>

    </div>
    <div>
        <section class="servicos-section">
            <table>
                <tbody>
                    {% for servico in servicos %}
                        <tr>

                            <td>{{ servico.nome_servico }}</td>
                            <td>Duração: {{ servico.duracao_horas }}h {{ servico.duracao_minutos }}min</td>
                            <td> <div class="buttons">

                                <button id ="lapis" class="abrirModal2" hx-get={% url 'medico:editar-servico' profissional_pk=profissional.pk servico_pk=servico.pk %} hx-trigger='click' hx-target='.modal2' hx-swap="innerHTML">
                                    <img src="{% static 'assets/img/icons/pencil.svg'%}" alt="lapis de edição">
                                  </button> 
                                
                                <a href="{% url 'medico:excluir-servico' servico_pk=servico.pk profissional_pk=profissional.pk%}"><button class="lixeira"><img src="{% static 'assets/img/icons/trash.svg'%}" alt="lixeira"></button></a>
                            </div>
                        </td>
                            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </div>
</section>
</main>
</div>
</body>
</html>

apps/medico/templates/medico/cadastrar-servicos.html
{% load static %}
{% extends "base_home_atendente.html" %}
<section class="card-info">
    <div class="card-header">
        <h2>Serviços Oferecidos</h2>
        <button class="add-service" id="abrirModal" hx-get={% url 'medico:criar-servico' profissional_id= profissional.id  %} hx-trigger='click' hx-target='#modal' hx-swap="innerHTML">
            <i class="ph ph-user-circle-plus"></i>
            + Novo Serviço
          </button>

        <dialog class="cadastro-de-paciente" id="myModal">
            <div id="modal">
            </div>
        </dialog>
    </div>

    <div class="sections">
        <section class="servicos-section">
            <ul id="lista-servicos">
                {% for servico in servicos %}
                <a href = ""><li> {{ servico.nome_servico }} - {{ servico.duracao_servico }}</li></a>
                {% endfor %}
            </ul>
        </section>
    </div>
</section>

apps/medico/templates/medico/listar_profissionais.html
{% extends "base/base_home_atendente.html" %}
{% load static %}
{% block cadastrar_profissionais %}
<div class='endireitar'>
<div class="container-listagem">

        <div class="content-top">
            <h1>Gerenciar Profissionais</h1>
        </div>
            <section class="first-div">
                <div class = "nav-add">
                    <form method="GET">
                        <input type="search" name="search" placeholder="Buscar Profissionais" value="{{ request.GET.search }}">
                    </form>
                    <a href = "{% url 'medico:Cadastrar-Profissionais' %}"> <button class="cadastrar-paciente-button" >+ Novo Profissional</button></a>
                </div>
                    <div class="listagem-pacientes">
                        <ul>
                            {% for profissional in profissionais %}
                                <li>
                                    <a href = "{% url 'medico:detalhe-profissional' profissional_pk=profissional.pk %}"> 
                                    {% include "partials/card_profissional.html" %}
                                    </a>
                                </li>
                        {% endfor %}

                        </ul>
                    </div>
                </section>
                <div style='height: 50px'> 
                   
                </div>
                {% include "partials/pagination.html" %}
            </div>        
{% endblock cadastrar_profissionais %}

apps/medico/templates/medico/modal_add_service.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal">Criar Serviço</p> 
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'medico:criar-servico' profissional_pk=profissional.pk %}">

    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button">Cancelar</button>
      <button id="botao-salvar-paciente" type="submit">Salvar</button>
    </div>
  </form>
</div> 
<script src="{% static 'medico/js/modal.js' %}"></script>

apps/medico/templates/medico/modal_edit_service.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal">Criar Serviço</p> 
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'medico:editar-servico' servico_pk=servico.pk profissional_pk=profissional.pk %}">

    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente" type="submit">Salvar</button>
    </div>
  </form>

 </div> 
<script src="{% static 'medico/js/modal.js' %}"></script>

apps/medico/templates/medico/novo_profissional.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'atendente/css/novo-profissional.css' %}">
    <link rel="stylesheet" href="{% static 'perfil/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'medico/css/modal.css' %}">
    <script src="{% static 'medico/js/modal.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'perfil/css/modal.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.9" integrity="sha384-QFjmbokDn2DjBjq+fM+8LUIVrAgqcNW2s0PjAxHETgRn9l4fvX31ZxDxvwQnyMOX" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Gerenciar Profissionais</title>
</head>
<body>
    {% include "partials/header_icon_atendente.html" %}
    <div class="container">
        <h1>Cadastrar Profissional</h1>
    
            <section class="card-info">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-header">
                        <h2>Informações pessoais</h2>
                        <div class="buttons">
                            <button id="salvarButton">Salvar</button>
                            <button id="button-cancelar"><a href="#">Cancelar</a></button>
                        </div>
                    </div>
                    <div class="info-user">
            
                        {{ form.imagem }}
                           
                            <div>
                            <div class="first-section">
                                <div class="campos">
                                    <label for="nome">Nome</label>
                                    <p>{{ form.nome_medico }}</p>
                                </div>
                                <div class="campos">
                                    <label for="data">Registro Profissional</label>
                                    <p>{{ form.numero_registro }}</p>
                                </div>
                            </div>
                        <div class="sections">
                            <div class="second-section">
                                <div class="campos">
                                    <label for="e-mail">Especialidade</label>
                                    <p>{{ form.especialidade }}</p>
                                </div>
                            </div>
                            <div class="third-section">
                                <div class="campos">
                                    <label for="contato">Contato</label>
                                    <p>{{ form.contato_profissional }}</p>
                                </div>
                            </div>
                        </div>
                  
                </form>
            </section>
    

    </div>
    </div>

</body>
</html>

apps/medico/templates/medico/profissional.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'perfil/css/perfil.css' %}">
    <link rel="stylesheet" href="{% static 'perfil/css/header.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'perfil/js/perfil.js' %}"></script>
    <script src="{% static 'atendente/js/novo-profissional.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'perfil/css/modal.css' %}">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Gerenciar Profissionais</title>
</head>
<body>
    {% include "partials/header_icon_atendente.html" %}
    <div class="container">
        <h1>Gerenciar Profissionais</h1>
        <main>
            <section class="card-info">
                <div class="card-header">
                    <h2>Informações pessoais</h2>
                    <div class="buttons">
                        <button id="editButton">Editar</button>
                        <button id="button-excluir"><a href="{% url "medico:Cadastrar-Profissionais" %}">Excluir</a></button>
                    </div>
                </div>
                <div class="info-user">
                    <div class="first-section">
                        <div class="image-paciente">
                            <img src="{% static "assets/img/icons/medico-grande.svg" %}" alt="">
                        </div>
                        <div class="campos">
                            <label for="nome">Nome</label>
                            <p class="view-field">Kaio Moura</p>
                            <input type="text" class="edit-field" value="Kaio Moura" style="display: none;">
                        </div>
                        <div class="campos">
                            <label for="data">Data de Nascimento</label>
                            <p class="view-field">01/10/1984</p>
                            <input type="date" class="edit-field" value="1984-01-10" style="display: none;">
                        </div>
                    </div>
                    <div class="sections">
                        <div class="second-section">
                            <div class="campos">
                                <label for="e-mail">Especialidade</label>
                                <p class="view-field">Clínco Geral</p>
                                <input type="text" class="edit-field" value="Clínco Geral" style="display: none;">
                            </div>
                        </div>
                        <div class="third-section">
                            <div class="campos">
                                <label for="contato">Contato</label>
                                <p class="view-field">(84) 99999-9999</p>
                                <input type="text" class="edit-field" value="(84) 99999-9999" style="display: none;">
                            </div>
                    </div>
                </div>
            </div>
            </section>

            <section class="card-info">
                <div class="card-header">
                    <h2>Serviços Oferecidos</h2>
                    <button id="add-service" data-toggle="modal" data-target="#modalAddService"> + Adicionar Serviço</button>
                </div>
                <div class="sections">
                    <section class="servicos-section">
                        <ul id="lista-servicos">
                            <li> Consulta (30min)<button class="delete-service" style="display: none;">x</button></li>
                        </ul>
                        <input type="text" id="novo-servico" placeholder="Novo Serviço">
                    </section>
                </div>
            </section>
        </main>
    </div>
</body>
</html>