EspacoVivenciar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("apps.core.urls")),
    path('', include("apps.perfil.urls")),
    path('', include("apps.atendente.urls")),
    path('', include("apps.medico.urls")),
    path('', include("apps.paciente.urls")),
    path('', include("apps.agenda_medico.urls")),
    path('', include("apps.agendamento.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/agendamento/urls.py
from django.urls import path
from . import views

app_name = 'agendamento'

urlpatterns = [
    path('criar-agendamento/<int:horario_pk>/', views.CriarAgendamento.as_view(), name='criar-agendamento'), 
    path('agenda/agendamentos/<int:agenda_pk>/', views.ListarAgendamentosSolicitacoes.as_view(), name='listar-agendamentos'),
    path('aceitar_recusar_solicitacao/<int:solicitacao_id>/<str:action>/', views.AceitarRecusarSolicitacaoView.as_view(), name='aceitar_recusar_solicitacao'),
    path('solicitar-agendamento/<int:horario_pk>/', views.CriarSolicitacao.as_view(), name='solicitar-agendamento'),

]

apps/paciente/urls.py
from django.urls import path
from . import views

app_name = 'paciente'

urlpatterns = [

    path("atendente/pacientes/", views.ListarPacientes.as_view(), name="listar-pacientes"),
    path("atendente/pacientes/criar", views.CriarPaciente.as_view(), name="criar-paciente"),
    path("atendente/pacientes/excluir/<int:id>", views.ExcluirPaciente.as_view(), name="excluir-paciente"),
    path("atendente/pacientes/editar/<int:id>", views.EditarPaciente.as_view(), name="editar-paciente"),
    path("paciente/home/", views.Home.as_view(), name="Home"),
    
    path('paciente/selecionar-agenda/<int:profissional_pk>/', views.SelecionarAgendaView.as_view(), name='selecionar_agenda'),
    path('paciente/agenda/<int:profissional_pk>/<int:servico_id>/', views.ListarAgenda.as_view(), name='listar-agendas'),
    path('agenda/solicitar/<int:agenda_id>', views.ListarHorarios.as_view(), name='listar-horarios-atendimento'),
      
]

apps/paciente/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator, validate_integer
from django import forms
from django.conf import settings

class Paciente(models.Model):

    GENERO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('Outro', 'Outro')
    ]

    nome_paciente = models.CharField('Nome', max_length = 200)
    data_nascimento = models.DateField('Data de Nascimento')
    genero = models.CharField('Sexo', max_length=24, choices = GENERO_CHOICES, null = True)
    contato_paciente = models.CharField('Contato', max_length = 15, unique = True, null = True)
    cpf_paciente = models.CharField(
        max_length = 11,
        unique = True,
        null = True,
        verbose_name='Cpf',
        validators=[
            validate_integer,
            MinLengthValidator(limit_value = 11, message ='O CPF deve ter exatamente 11 dígitos.'),
            MaxLengthValidator(limit_value = 11, message ='O CPF deve ter exatamente 11 dígitos.'),
        ]
    )
    def get_genero_display_full(self):
    # Mapeie o valor do gênero para o nome completo
        genero_mapping = dict(self.GENERO_CHOICES)
        return genero_mapping.get(self.genero, self.genero)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    
    def __str__(self):
        return f'Nome: {self.nome_paciente} CPF: {self.cpf_paciente}'
    
    def clean_cpf(self):
        cpf_paciente = self.cleaned_data['cpf_paciente']
        if len(cpf_paciente) != 11:
            raise forms.ValidationError('O CPF deve ter exatamente 11 caracteres.')
        return cpf_paciente

apps/paciente/forms.py
from django import forms
from apps.paciente.models import Paciente
from betterforms.multiform import MultiModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class PacienteForm(forms.ModelForm):
    nome_paciente = forms.CharField(
        label="Nome do Paciente",
        widget=forms.TextInput(attrs={'class': 'edit-field'}),
    )

    data_nascimento = forms.DateField(
        label="Data de Nascimento",
        widget=forms.DateInput(attrs={'class': 'edit-field', 'type': 'date'}),
    )

    cpf_paciente = forms.CharField(
        label="Cpf",
        widget=forms.TextInput(attrs={'class': 'edit-field', 'maxlength': '11'}),
    )

    genero = forms.ChoiceField(
        label="Gênero",
        choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')],
        widget=forms.Select(attrs={'class': 'edit-field'}),
    )

    contato_paciente = forms.CharField(
        label="Contato",
        widget=forms.TextInput(attrs={'class': 'edit-field'}),
    )

    class Meta:
        model = Paciente
        fields = ['nome_paciente', 'data_nascimento', 'cpf_paciente', 'genero', 'contato_paciente']

    def save(self, commit=True):
        # Garante que a instância do paciente esteja associada ao formulário antes de salvar
        paciente = super().save(commit=False)
        paciente.nome_paciente = self.cleaned_data['nome_paciente']
        paciente.data_nascimento = self.cleaned_data['data_nascimento']
        paciente.cpf_paciente = self.cleaned_data['cpf_paciente']
        paciente.genero = self.cleaned_data['genero']
        paciente.contato_paciente = self.cleaned_data['contato_paciente']

        if commit:
            paciente.save()

        return paciente

class PerfilUserForm(UserCreationForm):
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={'class': 'edit-field'}),
    )

    password1 = forms.CharField(
        label=("Senha"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'edit-field'}),
        help_text="Your password cannot be similar to the rest of your personal information.",
    )

    password2 = forms.CharField(
        label="Confirmar senha",
        widget=forms.PasswordInput(attrs={'class': 'edit-field'}),
        strip=False,
        help_text="Enter the same password entered previously for verification.",
    )

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

class UserProfileMultiForm(MultiModelForm):
    form_classes = {
        'perfiluser': PerfilUserForm,
        'pacienteuser': PacienteForm,
    }

apps/paciente/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, DetailView, ListView, FormView
from .forms import UserProfileMultiForm, PerfilUserForm
from apps.paciente.models import Paciente
from apps.medico.models import Profissional
from django.db.models import Q
from .forms import PacienteForm
from apps.agenda_medico.forms import SelecionarAgendaForm
from apps.agenda_medico.models import AgendaMedica, Horario
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
import re
from apps.perfil.views import CreateUserAndPacienteMixin
from django.contrib.auth import get_user_model
User = get_user_model()


class Home(LoginRequiredMixin, ListView):
    model = Profissional
    template_name = 'paciente/home.html'
    context_object_name = 'profissionais'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        paciente = self.request.user
        context["paciente"] = paciente
    
        return context


class SelecionarAgendaView(FormView):
    template_name = 'paciente/modal_selecionar_agenda.html'
    form_class = SelecionarAgendaForm
    pk_url_kwarg = 'profissional_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        context['profissional'] = profissional
        context['servicos'] = profissional.servico_set.all()
        return context

    def form_valid(self, form):
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        servico = form.cleaned_data['servico']
        
        self.cleaned_data = {'servico': servico}

        return super().form_valid(form)

    def get_success_url(self):
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        servico = self.cleaned_data['servico']

        return reverse_lazy('paciente:listar-agendas', kwargs={'profissional_pk': profissional_pk, 'servico_id': servico.id})

    def get_form_kwargs(self):
        kwarg = super().get_form_kwargs()
        profissional_pk = self.kwargs.get('profissional_pk')
        profissional = Profissional.objects.get(pk=profissional_pk)
        kwarg['profissional'] = profissional
        return kwarg


class ListarAgenda(LoginRequiredMixin, ListView):
    model = AgendaMedica
    template_name = 'paciente/listar-agendas.html'
    context_object_name = 'agendas'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profissional_pk = self.kwargs.get('profissional_pk')
        servico_id = self.kwargs.get('servico_id')
        profissional = Profissional.objects.get(pk=profissional_pk)
        context['profissional'] = profissional
        context['servico'] = profissional.servico_set.get(id=servico_id)
        context['agendas'] = profissional.agendamedica_set.filter(servico=context['servico'])
        context['servico_id'] = servico_id
        context['profissional_pk'] = profissional_pk

        for agenda in context['agendas']:
            agenda.dia_semana_abreviado = listar_dias_semana(agenda)

        return context
        
def listar_dias_semana(agenda):
    dias_da_semana = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom']
    dia_semana_numero = agenda.data.weekday()
    return dias_da_semana[dia_semana_numero]

class ListarHorarios(LoginRequiredMixin, ListView):
    model = Horario
    template_name = 'paciente/listar-horarios-atendimento.html'
    context_object_name = 'horarios'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        agenda_id = self.kwargs.get('agenda_id')
        agenda = AgendaMedica.objects.get(id=agenda_id)
        context['agenda'] = agenda
        context['dia_semana_abreviado'] = listar_dias_semana(agenda)
        return context

    def get_queryset(self):
        agenda_id = self.kwargs.get('agenda_id')
        return Horario.objects.filter(agenda_medica__id=agenda_id)
    
class ListarPacientes(LoginRequiredMixin, ListView):
    model = Paciente
    template_name = 'paciente/pacientes.html'
    context_object_name = 'pacientes'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('search')

        object_list = Paciente.objects.all()
        if query:
            object_list = object_list.filter(Q(nome_paciente__icontains=query) | Q(cpf_paciente__icontains=query))
            
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Formata o CPF de cada paciente na lista
        for paciente in context['pacientes']:
            paciente.cpf_formatado = formatar_cpf(paciente.cpf_paciente)

        return context

def formatar_cpf(cpf):
    # Remove caracteres não numéricos do CPF
    cpf_numerico = re.sub('[^0-9]', '', str(cpf))

    # Formata o CPF
    cpf_formatado = '{}.{}.{}-{}'.format(cpf_numerico[:3], cpf_numerico[3:6], cpf_numerico[6:9], cpf_numerico[9:])
    
    return cpf_formatado

class CriarPaciente(LoginRequiredMixin, CreateUserAndPacienteMixin, CreateView):
    template_name = 'paciente/criar-paciente.html'
    form_class = UserProfileMultiForm
    success_url = reverse_lazy('paciente:listar-pacientes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paciente_form'] = PacienteForm()
        return context

    def get_user(self, user):
        return self.request.user

class ExcluirPaciente(DeleteView):
    model = Paciente
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('paciente:listar-pacientes')

    def get(self, *args, **kwargs):
        return self.delete(*args, **kwargs)

class EditarPaciente(LoginRequiredMixin, UpdateView):
    model = Paciente
    template_name = 'paciente/editar-paciente.html'
    form_class = PacienteForm
    pk_url_kwarg = 'id'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.get_object()
        if 'data_nascimento' in kwargs['instance'].__dict__:
            kwargs['instance'].data_nascimento = str(kwargs['instance'].data_nascimento)
        return kwargs
        

    def form_valid(self, form):
        # Save both user and paciente instances
        form.save()
        return super().form_valid(form)
    

    def get_success_url(self):
        return reverse_lazy('paciente:listar-pacientes')

apps/paciente/templates/paciente/card-agenda.html
<div class="card-item-hora1">
    <div class = "card-first3">{% load static %}
    <div class= 'card-first-1'>

        <div class="data-hr">
            <div class="data">
                <h2>{{ agenda.dia_semana_abreviado }}</h2>
                <h3>{{ agenda.data.day }}</h3>
            </div>
            <hr>
        </div>
            <div class="user">
                <p class = "name">{{ agenda.profissional.nome_medico}}<p>
                <p class = 'especialidade'>{{ agenda.profissional.especialidade}}</p>
            </div>
        </div>
    <div class="horario-solicitar">
        <p class="horario-atendimento">Horários de atendimento</p>
        <div class="horario">
            <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
            <p>{{ agenda.horario_inicio }}h  - {{ agenda.horario_fim }}h</p>
        </div>
    </div>

</div>
<a  href="{% url "paciente:listar-horarios-atendimento" agenda_id=agenda.id %}"><button class="button-detalhar2">Detalhar</button></a>
        
    </div>

apps/paciente/templates/paciente/card-horarios-atendimento.html
{% load static %}
<div class="card-item-hora">
    <div class = "card-first">
            <div class= 'card-first-1'>
            <div class="data-hr">
                <div class="data2">
                    <h2>{{ dia_semana_abreviado }}</h2>
                    <h3>{{ agenda.data.day }}</h3>
                </div>
                <hr id ='hr'>
            </div>

            <div class="user">
                <p class = "name">{{ agenda.profissional.nome_medico}}<p>
                <p class = 'especialidade'>{{ agenda.profissional.especialidade}}</p>
            </div>
    </div>

    <div class="horario-solicitar">
        <p class="horario-atendimento">Tempo de duração</p>
        <div class="horario">
            <img src="{% static "assets/img/icons/hora.svg" %}" alt="">
            <p class = 'hora'>{{ horario.inicio }}h  - {{ horario.fim}}h</p>
        </div>
    </div>
</div>

<div class="space-buttons">
    <div class="buttons">

<form method="post" action="{% url 'agendamento:solicitar-agendamento' horario_pk=horario.pk %}">
    {% csrf_token %}
    <button id='lapis' type="submit">
        <img src="{% static 'assets/img/icons/CalendarPlus.svg' %}" alt="lapis de edição"> Solicitar
    </button>
</form>

        
    </div>
</div>
</div>

apps/paciente/templates/paciente/criar-paciente.html
{% extends "base/base_home_atendente.html" %}
{% load static %}
{% block gerenciar_pacientes %}
<div class="container">
    <form method="post">
    {% csrf_token %}
        <h1>Cadastrar Paciente</h1>
    <section class="card-info">
        <div class="card-header">
            <h2>Informações pessoais</h2>
            <button type="submit" id="editButton">Salvar</button>
        </div>
        <div class="info-user">
            <div class="sections">
                <div class="section">
                    <div class="campos">
                        <label for="nome">Nome</label>
                        {{ form.pacienteuser.nome_paciente }}
                    </div>
                    <div class="campos">
                        <label for="data">Data de Nascimento</label>
                        {{ form.pacienteuser.data_nascimento }}
                    </div>
                </div>
                
                <div class="section">
                    <div class="campos">
                        <label for="gênero">Gênero</label>
                        {{ form.pacienteuser.genero }}
                    </div>
                
                    <div class="campos">
                        <label for="e-mail">E-mail</label>
                        {{ form.perfiluser.email }}
                    </div>
                </div>

                <div class="section">
                    <div class="campos">
                        {{ form.perfiluser.password1.label_tag }}
                        {{ form.perfiluser.password1 }}
                    </div>
                    <div class="campos">
                        {{ form.perfiluser.password2.label_tag }}
                        {{ form.perfiluser.password2 }}
                    </div>
                </div>
                
                <div class="section">
                    <div class="campos">
                        <label for="cpf">CPF</label>
                        {{ form.pacienteuser.cpf_paciente }}
                        {{ form.pacienteuser.cpf_paciente.errors }}
                    </div>
                
                    <div class="campos">
                        <label for="contato">Contato</label>
                        {{ form.pacienteuser.contato_paciente }}
                    </div>
                </div>
        </div>
        
    </section>
</form>
</div>
{% endblock gerenciar_pacientes %}

apps/paciente/templates/paciente/editar-paciente.html
{% extends "base/base_home_atendente.html" %}
{% load static %}
{% block gerenciar_pacientes %}
<div class="container">
    <form method="post">
    {% csrf_token %}
        <h1>Editar Paciente</h1>
        <section class="card-info">
            <div class="card-header">
                <h2>Informações pessoais</h2>
                <button type="submit" id="editButton">Salvar</button>
            </div>
            <div class="info-user">
                <div class="sections">
                    <div class="section">
                        <div class="campos">
                            <label for="nome">Nome</label>
                            {{ form.nome_paciente }}
                        </div>
                        <div class="campos">
                            <label for="data">Data de Nascimento</label>
                            {{ form.data_nascimento }}
                        </div>
                    </div>
                    
                    <div class="section">
                        <div class="campos">
                            <label for="gênero">Gênero</label>
                            {{ form.genero }}
                        </div>
                        <div class="campos">
                            <label for="cpf">CPF</label>
                            {{ form.cpf_paciente }}
                            {{ form.cpf_paciente.errors }}
                        </div>
                    </div>
                    
                    <div class="section">
                    
                        <div class="campos">
                            <label for="contato">Contato</label>
                            {{ form.contato_paciente }}
                        </div>
                    </div>
            </div>
            
        </section>
        
</form>
</div>
{% endblock gerenciar_pacientes %}

apps/paciente/templates/paciente/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'perfil/css/home.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/carousel.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'medico/css/modal.css' %}">
    <link rel="stylesheet" href="{% static 'perfil/css/header.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <script src="https://unpkg.com/htmx.org@1.9.9" integrity="sha384-QFjmbokDn2DjBjq+fM+8LUIVrAgqcNW2s0PjAxHETgRn9l4fvX31ZxDxvwQnyMOX" crossorigin="anonymous"></script>
    <script src="{% static "medico/js/modal.js" %}" defer></script>

    <script src="{% static "perfil/js/index.js" %}" defer></script>
    <title>Espaço Vivenciar - Home</title>
</head>
<body>
  {% include "partials/header_icon.html" %}
  
  <main>
    <dialog class="myModal8">
      <div id="modal8">
      </div>
    </dialog>
        <div class="container">
            <div class="home-info">
                <p>Bem-vindo(a), {{ paciente }}!</p>
                <h1>Solicite um Agendamento</h1>
                <br>
                <p>Escolha um especialista e solicite seu <br> agendamento.</p>
            </div>

            <div class="home-img">
                <img src="{% static "assets/img/home-img.svg" %}" alt="">
            </div>
        </div>
        
        <div class="wrapper">
          <i id="left" class="fa-solid fa-angle-left"></i>
          <ul class="carousel">
            {% for profissional in profissionais %}
        
            <button class="abrirModal8" hx-get="{% url 'paciente:selecionar_agenda' profissional_pk=profissional.pk %}"
              hx-trigger='click' hx-target='#modal8' hx-swap="innerHTML">
              <li class="card">
                {% include "partials/card-carousel.html" %}
              </li>
            </button>
        
            {% endfor %}
          </ul>
          <i id="right" class="fa-solid fa-angle-right"></i>
        </div>
    </main>
</body>
</html>

apps/paciente/templates/paciente/listar-agendas.html
{% extends "base/base_home.html" %}
{% load static %}
{% block main %}

{% if messages %}
                <script>
                    window.alert("{% for message in messages %}{{ message }}\n{% endfor %}");
                </script>
{% endif %}
</div>
<div class="container">
    <div class="card-list">
        <div class="title">
            <h1>Agenda - {{ servico.nome_servico }}  </h1>
        </div>
        <div class="content">
            
                
                <div class="data-alternada">
                    <p>Dezembro</p>
                </div>
                
                    
                </div>

                {% for agenda in agendas %}
                    {% include "paciente/card-agenda.html"   %}
                {% endfor %}

        </div>

    </div>
{% endblock main %}

apps/paciente/templates/paciente/listar-horarios-atendimento.html
{% extends "base/base_home.html" %}
{% load static %}
{% block main %}
    <div class="container">
        
        <div class="card-list">
            
            <div class="title">
                <h1>Horários disponíveis - {{ agenda.servico.nome_servico }}  </h1>
            </div>

            {% for horario in horarios %}
                    {% include "paciente/card-horarios-atendimento.html"   %}
            {% endfor %}

        </div>
        
    </div>
    {% include "partials/pagination.html" %}

{% endblock main %}

apps/paciente/templates/paciente/modal_selecionar_agenda.html
{% load static %}
<div class="conteudo-modal">
  <p class="titulo-modal">Selecionar agenda</p> 
  <form class="formulario-paciente" id="formAdicionarServico" method="post" action="{% url 'paciente:selecionar_agenda' profissional_pk=profissional.pk %}">

    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    
    <div class="footer-modal-criar-paciente">
      <button class="fecharModal" type="button" >Cancelar</button>
      <button id="botao-salvar-paciente" type="submit">Confirmar</button>
    </div>
  </form>
 </div> 

apps/paciente/templates/paciente/pacientes.html
{% extends "base/base_home_atendente.html" %}
{% load static %}
{% block gerenciar_pacientes %}
<div class='endireitar'>
    <div class="container-listagem">
            <div class="content-top">
                <h1>Gerenciar Pacientes</h1>
            </div>
            <section class="first-div">
                <div class="nav-add">
                    <form method="get">
                        <input type="search" name="search" placeholder="Buscar Paciente" value="{{ request.GET.search }}" >
                    </form>
                    <a href="{% url 'paciente:criar-paciente' %}">
                        <button class="cadastrar-paciente-button">+ Novo Paciente</button>
                    </a>
                </div>
                <div class="listagem-pacientes">
                    <ul>
                        {% for paciente in pacientes %}
                            <li>
                                {% include "partials/card_listar_paciente.html" %}
                            </li>
                        {% endfor %}
                    </ul>
                </div> 
                {% include "partials/pagination.html" %}
            </section>
        </div>
<div>
{% endblock gerenciar_pacientes %}